version: "3.9"
services:
  db:
    image: postgres
    container_name: 'db'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - dev.env
    networks:
      - mainnetwork
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    networks:
      - mainnetwork
    depends_on:
      - db

networks:
  mainnetwork:
    name: "mainnetwork"